#Example configuration options that can be placed in your main SiriProxy config.yml

##########################
#NOTICE: Modifying these options in this file has no effect. You must put them in SiriProxy's config.yml!
##########################
    
    - name: 'NiraProxy'
      git: 'git://github.com/Niranda/SiriProxy-NiraProxy.git'
      auth_level: '0'
      user_id: 'default'
      user_secret: 'default'
      remind_on_update: true